services:
  project-db:
    container_name: postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: bachar
      POSTGRES_PASSWORD: password
      PGDATA: /data/project-db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  fullstack-api:
    container_name: fullStack-API
    image: bdaowd/fullstack-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://project-db:5432/customer
    ports:
      - "801188:8080"
    networks:
      - postgres
    depends_on:
      - project-db
    restart: unless-stopped
  bachar-frontend-react:
    container_name: bachar-frontend-react
    image: bdaowd/fullstack-react
    build:
      context: frontend/appFrontendReact
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - fullstack-api
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
  postgres: